version: '3.8'

services:
  racer:
    container_name: racer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1000:1000"
    networks:
      - blur
    restart: on-failure

  db2:
    image: postgres
    container_name: db2
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - blur
    volumes:
      - psql:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  blur:
    driver: bridge

volumes:
  psql:
