http_server:
  port: 1001
  host: localhost
  timeout: 4s
  idle_timeout: 60s
postgres:
  port: 5432
  host: localhost
  database: typeracer
  user: postgres
  url: postgres://postgres:Cicada_3301@localhost:5432/typeracer
base_url: http://localhost