http_server:
  port: 8080
  host: localhost
  timeout: 4s
  idle_timeout: 60s
postgres:
  port: 5431
  host: localhost
  database: typeracer
  user: postgres
  password: Cicada_3301
  url: postgres://postgres:Cicada_3301@localhost:5431/typeracer


