http_server:
  port: 1001
  host: localhost
  timeout: 4
  idle_timeout: 60
  header_timeout: 5
postgres:
  port: 5432
  host: localhost
  database: typeracer
  user: postgres
multiple:
  timer: 20
  max_racers: 5
